// dsh-fleet-mesh — the canonical wire body, asserted against PYTHON'S OWN BYTES.
//
// The vectors in `vectors/pyjson-vectors.json` were generated by Python 3.14's
// `json.dumps({"from":…, "text":…}, sort_keys=True)` — not written by hand, and not derived from
// my own encoder. That matters: the whole point is to catch the places where JavaScript's JSON and
// Python's differ, and a vector I wrote myself would encode my own misunderstanding.
//
// The expected value is stored as HEX rather than as the string, because a JSON file cannot carry
// `\u2014` through a parse — `JSON.parse` would decode the escape and the test would be asserting
// against the wrong bytes while looking correct.
//
// Why this is security-relevant rather than cosmetic: the receiver verifies the Ed25519 signature
// over the bytes it RECEIVED. One character of difference between what I sign and what Python
// would have produced is a failed verification at the far end, not a formatting quibble.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pyJsonString, unwrapJsonWireBody, wrapJsonWireBody } from '../lib/pyjson.mjs';

let pass = 0;
let fail = 0;
const eq = (name, actual, expected) => {
	const a = JSON.stringify(actual);
	const e = JSON.stringify(expected);
	if (a === e) {
		pass += 1;
		console.log(`  ok   ${name}`);
	} else {
		fail += 1;
		console.log(`  FAIL ${name}\n         expected ${e}\n         actual   ${a}`);
	}
};
const ok = (name, value) => eq(name, Boolean(value), true);

const here = dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(readFileSync(join(here, 'vectors', 'pyjson-vectors.json'), 'utf8'));

const hexOf = (s) => Buffer.from(s, 'utf8').toString('hex');

console.log(`\npyjson — the canonical wire body (vectors from ${vectors.generator})`);

eq('the vector file has a usable spread', vectors.vectors.length >= 13, true);

for (const v of vectors.vectors) {
	const produced = wrapJsonWireBody(v.from, v.text);
	eq(`wrap matches Python byte-for-byte — ${v.name}`, hexOf(produced), v.hex);
}

// The properties those vectors exist to pin, stated once more in words so a future reader does not
// have to reverse them out of hex.
ok('ascii output only (ensure_ascii)', /^[\x20-\x7e]*$/.test(wrapJsonWireBody('lily', '温石の間 — 🐉')));
ok('spaced separators, not compact', wrapJsonWireBody('lily', 'x').startsWith('{"from": "lily", "text": '));
ok('astral characters become a surrogate pair', wrapJsonWireBody('lily', '🐉').includes('\\ud83d\\udc09'));
ok('hex is lowercase', wrapJsonWireBody('lily', 'ÿ').includes('\\u00ff'));
ok('DEL is escaped (> 0x7e)', wrapJsonWireBody('lily', '\x7f').includes('\\u007f'));
ok('forward slash is NOT escaped', wrapJsonWireBody('lily', 'a/b').includes('a/b'));
ok('backslash is doubled', pyJsonString('a\\b') === '"a\\\\b"');
ok('short escapes are used', pyJsonString('\t\n\r\b\f') === '"\\t\\n\\r\\b\\f"');

console.log('\npyjson — unwrapping, and the legacy form');

const round = unwrapJsonWireBody(wrapJsonWireBody('daji', '[mesh] hello — 温石'));
eq('a wrapped body unwraps to its sender', round?.from, 'daji');
eq('and its envelope text', round?.text, '[mesh] hello — 温石');
eq('a raw legacy body is NOT mistaken for json', unwrapJsonWireBody('[mesh][v:1][from:lily]hi'), null);
eq('nor is a non-object', unwrapJsonWireBody('"just a string"'), null);
eq('nor is malformed json', unwrapJsonWireBody('{"from": "x", '), null);
eq('nor an object without text', unwrapJsonWireBody('{"from": "x"}'), null);
eq('empty text unwraps (falsy is not absent)', unwrapJsonWireBody('{"from": "x", "text": ""}')?.text, '');
eq('a missing from is tolerated', unwrapJsonWireBody('{"text": "x"}')?.from, null);

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
