// dsh-fleet-mesh — Python-compatible JSON encoding for the canonical wire body.
//
// The fleet's canonical wire body is
//
//     json.dumps({"from": <sender>, "text": <envelope>}, sort_keys=True)
//
// (hermes_mesh/session_relay.py L362, wire_format="json" — the DEFAULT). Python's defaults are
// not JavaScript's, and the receiver verifies the signature over the bytes it RECEIVED
// (adapter.py `_verify_ed25519(request, body, …)`), so these bytes must match exactly. A single
// differing character is a failed verification, not a cosmetic difference:
//
//   * separators are ", " and ": " — spaced, not compact (canonicalize_json uses the compact
//     form, which is a DIFFERENT contract for a different artifact — the trust record);
//   * ensure_ascii=True, so every character above 0x7E becomes \uXXXX with LOWERCASE hex;
//   * astral characters become a surrogate PAIR (\ud83d\udc09), not a code point;
//   * "\b \f \n \r \t" use short escapes; "/" is NOT escaped.
//
// Every rule here is asserted against bytes generated by Python itself — see
// test/pyjson.test.mjs, whose vectors were produced by `py` (3.14) rather than by hand.

/** Python's short escapes, and the only characters that use them. */
const SHORT = new Map([
	[0x08, '\\b'],
	[0x09, '\\t'],
	[0x0a, '\\n'],
	[0x0c, '\\f'],
	[0x0d, '\\r'],
]);

const hex4 = (n) => n.toString(16).padStart(4, '0');

/**
 * Encode one string exactly as Python's `json.dumps(..., ensure_ascii=True)` would.
 *
 * Iterates by CODE POINT, so an astral character arrives whole and is split into its surrogate
 * pair here rather than being mangled by UTF-16 unit indexing.
 */
export function pyJsonString(value) {
	let out = '"';
	for (const ch of String(value)) {
		const cp = ch.codePointAt(0);
		if (ch === '"') out += '\\"';
		else if (ch === '\\') out += '\\\\';
		else if (SHORT.has(cp)) out += SHORT.get(cp);
		else if (cp < 0x20 || cp > 0x7e) {
			if (cp > 0xffff) {
				const v = cp - 0x10000;
				out += `\\u${hex4(0xd800 + (v >> 10))}\\u${hex4(0xdc00 + (v & 0x3ff))}`;
			} else {
				out += `\\u${hex4(cp)}`;
			}
		} else out += ch;
	}
	return `${out}"`;
}

/**
 * The canonical wrap. `sort_keys=True` over exactly two keys that are already in order
 * (`from` < `text`), so the object's serialization is fixed.
 */
export function wrapJsonWireBody(from, body) {
	return `{"from": ${pyJsonString(from)}, "text": ${pyJsonString(body)}}`;
}

/**
 * Unwrap a canonical body received from a peer.
 *
 * Returns `{from, text}` for the JSON form, or `null` when the body is not it — which is how the
 * legacy `raw` form is recognised. The caller verifies the signature over the RAW bytes either
 * way, so this only decides what to PARSE, never what to trust.
 */
export function unwrapJsonWireBody(raw) {
	const trimmed = String(raw).trim();
	if (trimmed.startsWith('{') === false) return null;
	let parsed;
	try {
		parsed = JSON.parse(trimmed);
	} catch {
		return null;
	}
	if (!parsed || typeof parsed !== 'object' || typeof parsed.text !== 'string') return null;
	return { from: typeof parsed.from === 'string' ? parsed.from : null, text: parsed.text };
}
